// Fake API for patient data
import type { Patient } from '@/types';
import { RELATIONS } from '@/types';

export async function fetchPatients(): Promise<Patient[]> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 500));
  const rawPatients = [
    {
      id: '1',
      mrn: 'MRN001',
      firstName: 'Alice',
      lastName: 'Smith',
      dob: new Date('1990-05-15'),
      gender: 'Female',
      phone: '555-0101',
      email: 'alice.smith@example.com',
      address: '123 Oak St, Anytown',
      insuranceProvider: 'HealthFirst',
      insuranceNumber: 'HF123456',
      status: 'Active',
      notes: 'Diabetic. Needs regular checkups.',
      emergencyContact: {
        name: 'John Smith',
        relationId: 13,
        relationName: 'Friend',
        phone: '555-0199',
      },
      allergies: ['Penicillin'],
    },
    {
      id: '2',
      mrn: 'MRN002',
      firstName: 'Bob',
      lastName: 'Johnson',
      dob: new Date('1985-08-22'),
      gender: 'Male',
      phone: '555-0102',
      email: 'bob.johnson@example.com',
      address: '456 Pine St, Anytown',
      insuranceProvider: 'MediCare',
      insuranceNumber: 'MC654321',
      status: 'Inactive',
      notes: '',
      emergencyContact: {
        name: 'Sara Johnson',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0188',
      },
      allergies: [],
    },
    {
      id: '3',
      mrn: 'MRN003',
      firstName: 'Carol',
      lastName: 'Williams',
      dob: new Date('2000-01-30'),
      gender: 'Female',
      phone: '555-0103',
      email: 'carol.williams@example.com',
      address: '789 Maple St, Anytown',
      insuranceProvider: 'BlueCross',
      insuranceNumber: 'BC789012',
      status: 'Active',
      notes: 'Asthma.',
      emergencyContact: {
        name: 'Mike Williams',
        relationId: 1,
        relationName: 'Father',
        phone: '555-0177',
      },
      allergies: ['Peanuts'],
    },
    {
      id: '4',
      mrn: 'MRN004',
      firstName: 'David',
      lastName: 'Brown',
      dob: new Date('1978-11-03'),
      gender: 'Male',
      phone: '555-0104',
      email: 'david.brown@example.com',
      address: '101 Elm St, Anytown',
      insuranceProvider: 'Aetna',
      insuranceNumber: 'AE456789',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Linda Brown',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0166',
      },
      allergies: ['Latex'],
    },
    {
      id: '5',
      mrn: 'MRN005',
      firstName: 'Eve',
      lastName: 'Davis',
      dob: new Date('1995-07-19'),
      gender: 'Female',
      phone: '555-0105',
      email: 'eve.davis@example.com',
      address: '202 Birch St, Anytown',
      insuranceProvider: 'Cigna',
      insuranceNumber: 'CG321654',
      status: 'Active',
      notes: 'Hypertension.',
      emergencyContact: {
        name: 'Paul Davis',
        relationId: 4,
        relationName: 'Brother',
        phone: '555-0155',
      },
      allergies: [],
    },
    {
      id: '6',
      mrn: 'MRN006',
      firstName: 'Frank',
      lastName: 'Miller',
      dob: new Date('1982-03-12'),
      gender: 'Male',
      phone: '555-0106',
      email: 'frank.miller@example.com',
      address: '303 Cedar St, Anytown',
      insuranceProvider: 'UnitedHealth',
      insuranceNumber: 'UH654987',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Nancy Miller',
        relationId: 2,
        relationName: 'Mother',
        phone: '555-0144',
      },
      allergies: ['Shellfish'],
    },
    {
      id: '7',
      mrn: 'MRN007',
      firstName: 'Grace',
      lastName: 'Wilson',
      dob: new Date('1970-09-25'),
      gender: 'Female',
      phone: '555-0107',
      email: 'grace.wilson@example.com',
      address: '404 Spruce St, Anytown',
      insuranceProvider: 'Kaiser',
      insuranceNumber: 'KS987321',
      status: 'Inactive',
      notes: 'Recovering from surgery.',
      emergencyContact: {
        name: 'Tom Wilson',
        relationId: 13,
        relationName: 'Friend',
        phone: '555-0133',
      },
      allergies: [],
    },
    {
      id: '8',
      mrn: 'MRN008',
      firstName: 'Henry',
      lastName: 'Moore',
      dob: new Date('2002-12-11'),
      gender: 'Male',
      phone: '555-0108',
      email: 'henry.moore@example.com',
      address: '505 Willow St, Anytown',
      insuranceProvider: 'HealthFirst',
      insuranceNumber: 'HF852963',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Anna Moore',
        relationId: 2,
        relationName: 'Mother',
        phone: '555-0122',
      },
      allergies: ['Gluten'],
    },
    {
      id: '9',
      mrn: 'MRN009',
      firstName: 'Ivy',
      lastName: 'Taylor',
      dob: new Date('1998-06-14'),
      gender: 'Female',
      phone: '555-0109',
      email: 'ivy.taylor@example.com',
      address: '606 Aspen St, Anytown',
      insuranceProvider: 'MediCare',
      insuranceNumber: 'MC147258',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Sam Taylor',
        relationId: 1,
        relationName: 'Father',
        phone: '555-0111',
      },
      allergies: ['Soy'],
    },
    {
      id: '10',
      mrn: 'MRN010',
      firstName: 'Jack',
      lastName: 'Anderson',
      dob: new Date('1987-04-18'),
      gender: 'Male',
      phone: '555-0110',
      email: 'jack.anderson@example.com',
      address: '707 Poplar St, Anytown',
      insuranceProvider: 'BlueCross',
      insuranceNumber: 'BC963852',
      status: 'Active',
      notes: 'Allergic to cats.',
      emergencyContact: {
        name: 'Lisa Anderson',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0100',
      },
      allergies: ['Cats'],
    },
    {
      id: '11',
      mrn: 'MRN011',
      firstName: 'Karen',
      lastName: 'Thomas',
      dob: new Date('1992-10-05'),
      gender: 'Female',
      phone: '555-0111',
      email: 'karen.thomas@example.com',
      address: '808 Walnut St, Anytown',
      insuranceProvider: 'Aetna',
      insuranceNumber: 'AE741852',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Peter Thomas',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0198',
      },
      allergies: [],
    },
    {
      id: '12',
      mrn: 'MRN012',
      firstName: 'Leo',
      lastName: 'Jackson',
      dob: new Date('1975-02-28'),
      gender: 'Male',
      phone: '555-0112',
      email: 'leo.jackson@example.com',
      address: '909 Chestnut St, Anytown',
      insuranceProvider: 'Cigna',
      insuranceNumber: 'CG258369',
      status: 'Deceased',
      notes: 'Passed away 2023.',
      emergencyContact: {
        name: 'Mary Jackson',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0187',
      },
      allergies: [],
    },
    {
      id: '13',
      mrn: 'MRN013',
      firstName: 'Mona',
      lastName: 'White',
      dob: new Date('1989-08-09'),
      gender: 'Female',
      phone: '555-0113',
      email: 'mona.white@example.com',
      address: '1010 Hickory St, Anytown',
      insuranceProvider: 'UnitedHealth',
      insuranceNumber: 'UH369258',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Steve White',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0176',
      },
      allergies: ['Aspirin'],
    },
    {
      id: '14',
      mrn: 'MRN014',
      firstName: 'Nina',
      lastName: 'Harris',
      dob: new Date('1997-12-21'),
      gender: 'Female',
      phone: '555-0114',
      email: 'nina.harris@example.com',
      address: '1111 Magnolia St, Anytown',
      insuranceProvider: 'Kaiser',
      insuranceNumber: 'KS159357',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Paul Harris',
        relationId: 1,
        relationName: 'Father',
        phone: '555-0165',
      },
      allergies: [],
    },
    {
      id: '15',
      mrn: 'MRN015',
      firstName: 'Oscar',
      lastName: 'Martin',
      dob: new Date('1983-06-17'),
      gender: 'Male',
      phone: '555-0115',
      email: 'oscar.martin@example.com',
      address: '1212 Palm St, Anytown',
      insuranceProvider: 'HealthFirst',
      insuranceNumber: 'HF357159',
      status: 'Active',
      notes: 'High cholesterol.',
      emergencyContact: {
        name: 'Julia Martin',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0154',
      },
      allergies: ['Eggs'],
    },
    {
      id: '16',
      mrn: 'MRN016',
      firstName: 'Paula',
      lastName: 'Garcia',
      dob: new Date('1991-11-29'),
      gender: 'Female',
      phone: '555-0116',
      email: 'paula.garcia@example.com',
      address: '1313 Olive St, Anytown',
      insuranceProvider: 'MediCare',
      insuranceNumber: 'MC951753',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Carlos Garcia',
        relationId: 1,
        relationName: 'Father',
        phone: '555-0143',
      },
      allergies: [],
    },
    {
      id: '17',
      mrn: 'MRN017',
      firstName: 'Quinn',
      lastName: 'Martinez',
      dob: new Date('2001-03-03'),
      gender: 'Other',
      phone: '555-0117',
      email: 'quinn.martinez@example.com',
      address: '1414 Peach St, Anytown',
      insuranceProvider: 'BlueCross',
      insuranceNumber: 'BC753159',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Maria Martinez',
        relationId: 2,
        relationName: 'Mother',
        phone: '555-0132',
      },
      allergies: ['Tree nuts'],
    },
    {
      id: '18',
      mrn: 'MRN018',
      firstName: 'Rita',
      lastName: 'Clark',
      dob: new Date('1986-07-23'),
      gender: 'Female',
      phone: '555-0118',
      email: 'rita.clark@example.com',
      address: '1515 Cherry St, Anytown',
      insuranceProvider: 'Aetna',
      insuranceNumber: 'AE357951',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'George Clark',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0121',
      },
      allergies: [],
    },
    {
      id: '19',
      mrn: 'MRN019',
      firstName: 'Sam',
      lastName: 'Lewis',
      dob: new Date('1993-05-10'),
      gender: 'Male',
      phone: '555-0119',
      email: 'sam.lewis@example.com',
      address: '1616 Plum St, Anytown',
      insuranceProvider: 'Cigna',
      insuranceNumber: 'CG159753',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Helen Lewis',
        relationId: 2,
        relationName: 'Mother',
        phone: '555-0110',
      },
      allergies: ['Fish'],
    },
    {
      id: '20',
      mrn: 'MRN020',
      firstName: 'Tina',
      lastName: 'Walker',
      dob: new Date('1996-09-14'),
      gender: 'Female',
      phone: '555-0120',
      email: 'tina.walker@example.com',
      address: '1717 Apple St, Anytown',
      insuranceProvider: 'UnitedHealth',
      insuranceNumber: 'UH951357',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Mark Walker',
        relationId: 1,
        relationName: 'Father',
        phone: '555-0109',
      },
      allergies: [],
    },
    {
      id: '21',
      mrn: 'MRN021',
      firstName: 'Uma',
      lastName: 'Young',
      dob: new Date('1984-02-02'),
      gender: 'Female',
      phone: '555-0121',
      email: 'uma.young@example.com',
      address: '1818 Lemon St, Anytown',
      insuranceProvider: 'Kaiser',
      insuranceNumber: 'KS357951',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Victor Young',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0197',
      },
      allergies: ['Milk'],
    },
    {
      id: '22',
      mrn: 'MRN022',
      firstName: 'Victor',
      lastName: 'King',
      dob: new Date('1979-10-20'),
      gender: 'Male',
      phone: '555-0122',
      email: 'victor.king@example.com',
      address: '1919 Lime St, Anytown',
      insuranceProvider: 'HealthFirst',
      insuranceNumber: 'HF951357',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Wendy King',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0186',
      },
      allergies: [],
    },
    {
      id: '23',
      mrn: 'MRN023',
      firstName: 'Wendy',
      lastName: 'Scott',
      dob: new Date('1994-04-04'),
      gender: 'Female',
      phone: '555-0123',
      email: 'wendy.scott@example.com',
      address: '2020 Orange St, Anytown',
      insuranceProvider: 'MediCare',
      insuranceNumber: 'MC357951',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Victor Scott',
        relationId: 1,
        relationName: 'Father',
        phone: '555-0175',
      },
      allergies: ['Wheat'],
    },
    {
      id: '24',
      mrn: 'MRN024',
      firstName: 'Xander',
      lastName: 'Green',
      dob: new Date('1988-08-08'),
      gender: 'Male',
      phone: '555-0124',
      email: 'xander.green@example.com',
      address: '2121 Pear St, Anytown',
      insuranceProvider: 'BlueCross',
      insuranceNumber: 'BC159357',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Yara Green',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0164',
      },
      allergies: [],
    },
    {
      id: '25',
      mrn: 'MRN025',
      firstName: 'Yara',
      lastName: 'Baker',
      dob: new Date('1990-12-12'),
      gender: 'Female',
      phone: '555-0125',
      email: 'yara.baker@example.com',
      address: '2222 Fig St, Anytown',
      insuranceProvider: 'Aetna',
      insuranceNumber: 'AE159357',
      status: 'Active',
      notes: '',
      emergencyContact: {
        name: 'Zane Baker',
        relationId: 3,
        relationName: 'Spouse',
        phone: '555-0153',
      },
      allergies: ['Strawberries'],
    },
  ];
  return rawPatients.map((p) => ({
    ...p,
    gender: p.gender as 'Male' | 'Female' | 'Other',
    status: p.status as 'Active' | 'Inactive' | 'Deceased',
  }));
}
